### ISSUE TITLE
Text at the bottom of the homepage "(c) 2020....rights reserved" is overlapping Register button (Mobile only)

### ISSUE THREAD

**Issue by anunaykumar03** [launchtechllc/npocore#31] opened 2020-06-18 01:06 UTC
The copyright text overlaps the Register your NPO button and makes it difficult to click on the desired button. 

The bug only shows on mobile and not on Windows.

**Comment by MitchellArtz** [comment] 2020-06-18 19:09
Bug only occurs for me when the menu is open

**Comment by calixo888** [comment] 2020-06-18 21:01
@anunaykumar03 can you attach a screenshot for reference?

**Comment by anunaykumar03** [comment] 2020-06-18 21:03
![77F1047F-2599-42DD-8530-97FF41B10F45](https://user-images.githubusercontent.com/66542316/85071517-7b36e180-b16c-11ea-9220-a5f6f3979937.png)

**Comment by MitchellArtz** [comment] 2020-06-21 02:14
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed

**Closed by MitchellArtz** 2020-06-21 02:14 UTC
Labels: invalid
