### ISSUE TITLE
Allows user to set an organization's location to one that doesn't exist

### ISSUE THREAD

**Issue by angc7** [launchtechllc/npocore#59] opened 2020-06-19 05:20 UTC
- When setting a location, there is a dropdown list of locations matching the name around the world
- It is possible to enter and submit a location not on the list
- No failsafe validating authenticity of location
- In the screenshot, location is set as "somewhere"

<img width="1099" alt="Screen Shot 2020-06-19 at 1 16 35 AM" src="https://user-images.githubusercontent.com/65053157/85099263-f9c26c00-b1ca-11ea-9655-14a7a4973d16.png">

**Comment by MitchellArtz** [comment] 2020-06-21 02:19
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed

**Closed by MitchellArtz** 2020-06-21 02:19 UTC
Labels: enhancement, invalid
