### ISSUE TITLE
No Character Limit on Post Title, Post Content, and Post Button Text

### ISSUE THREAD

**Issue by rexliu3** [launchtechllc/npocore#40] opened 2020-06-18 01:32 UTC
I was able to input a super long string of characters, numbers, and string as a post; the title and button text showed in its entirety. This moved all other posts down a lot. 
Suggestions:
- Set a character limit on the post title, post content, and post button text
- Have a "read more" for the post title and post button text (already have one for post content)

**Comment by calixo888** [comment] 2020-06-18 21:12
Duplicate of #28

**Closed by calixo888** 2020-06-18 21:12 UTC
Labels: invalid
