### ISSUE TITLE
Organizations aren't showing

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/npocore#25] opened 2020-06-18 00:24 UTC
1. Go to https://www.npocore.com/organizations
2. Scroll down past the first row of organizations
3. Boom, the screen goes blank with just the background showing

**Comment by MitchellArtz** [comment] 2020-06-18 00:25
![OrgsNotShowing](https://user-images.githubusercontent.com/32065190/84963906-b4257680-b0d8-11ea-9a8d-85126f166b21.PNG)

**Comment by MitchellArtz** [comment] 2020-06-18 00:58
![image](https://user-images.githubusercontent.com/32065190/84965589-4b8cc880-b0dd-11ea-9493-57a7ed3507f8.png)
Seems to be reproduced on mobile as well

**Comment by hirshi001** [comment] 2020-06-18 01:24
It seems to happen when you scroll to the end of the page and there is no more content. I could reproduce this bug on a mac on both Chrome and Safari.

**Comment by hirshi001** [comment] 2020-06-18 01:30
When i looked at the html, it seems all the content in the div with id=“root” get removed somehow

**Comment by calixo888** [comment] 2020-06-18 21:13
@MitchellArtz That was a technical bug that was due to weird orgs being submitted - it's fixed now

**Closed by calixo888** 2020-06-18 21:13 UTC
Labels: bug
