### ISSUE TITLE
Opportunity Posts: Another filtering issue (references issue #18)

### ISSUE THREAD

**Issue by angc7** [launchtechllc/npocore#62] opened 2020-06-19 06:10 UTC
This issue can be closed, I just wanted to bring to light another issue with the opportunity post filtering that may not have been addressed or included already in issue #18.

When typing in a search query that does not match any posts (either title or content), it returns all of the posts instead of none, not sure if this is intended.

**Comment by MitchellArtz** [comment] 2020-06-21 02:22
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed

**Closed by MitchellArtz** 2020-06-21 02:22 UTC
Labels: invalid
