### ISSUE TITLE
Post creation: after uploading video, it does not display on the post & account is unusable

### ISSUE THREAD

**Issue by angc7** [launchtechllc/npocore#64] opened 2020-06-19 06:42 UTC
- Similar to issue #34, where setting too large of an organization's profile picture renders the account unusable.
- Uploading a video file to a post (mine was specifically 7.1mb) displays a light grey box instead of the video.
- After posting, when clicking the account information, it displays "Internal Server Error"
<img width="409" alt="Screen Shot 2020-06-19 at 2 40 10 AM" src="https://user-images.githubusercontent.com/65053157/85104224-33e53b00-b1d6-11ea-9e97-0f87727da08f.png">

Possible solution:
- Limiting file size on uploads where applicable.

**Comment by MitchellArtz** [comment] 2020-06-21 02:19
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed

**Closed by MitchellArtz** 2020-06-21 02:19 UTC
Labels: bug
