### ISSUE TITLE
invalid emails during registration

### ISSUE THREAD

**Issue by mollyxu** [launchtechllc/npocore#30] opened 2020-06-18 01:05 UTC
Allows users to input invalid emails (eg. 123@123) as long as it's in the format of "text@text". 

Suggestions:
- ensures that "@" is followed by "gmail.com", "hotmail.com" etc. before the user is allowed to press the register button
- display "please enter a valid email address" if the email is invalid

**Comment by RafaelCenzano** [comment] 2020-06-18 20:31
Custom domains require things besides just gmail, hostmail, etc.

**Comment by calixo888** [comment] 2020-06-18 20:57
@mollyxu I think I've gotten this brought up before. It's a matter of whoever is registering, if they're not going to put in a valid email than they can't really use NPO core the right way

**Comment by MitchellArtz** [comment] 2020-06-21 02:12
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed

**Closed by MitchellArtz** 2020-06-21 02:12 UTC
Labels: invalid
