### ISSUE TITLE
Opportunity - Opportunity Posts - filter doesn't sort properly

### ISSUE THREAD

**Issue by mollyxu** [launchtechllc/npocore#39] opened 2020-06-18 01:26 UTC
When any of the filters from this drop-down bar is applied, the opportunities are not sorted properly by the filter. 
![Screen Shot 2020-06-17 at 6 18 05 PM](https://user-images.githubusercontent.com/64995721/84966663-e62ddd00-b0c6-11ea-80be-e4fee2489a27.png)

Although most opportunities at the top are sorted, as the user scrolls down to the bottom, opportunities are mixed.

eg. the "announcement" opportunities at the top are sorted  
![Screen Shot 2020-06-17 at 6 20 47 PM](https://user-images.githubusercontent.com/64995721/84966806-46248380-b0c7-11ea-8c83-9eaa360f392e.png)

the "announcement" opportunities near the bottom of the page become entangled with "job opening" and "opportunity"
![Screen Shot 2020-06-17 at 6 25 05 PM](https://user-images.githubusercontent.com/64995721/84967040-e084c700-b0c7-11ea-9e9a-cbfa573f15aa.png)

**Comment by calixo888** [comment] 2020-06-18 21:09
Duplicate of #18

**Closed by calixo888** 2020-06-18 21:09 UTC
Labels: invalid
