### ISSUE TITLE
Post creation: button colour can be set to white

### ISSUE THREAD

**Issue by angc7** [launchtechllc/npocore#61] opened 2020-06-19 05:43 UTC
- In terms of UI and overall look, setting the button to white allows it to blend into the white post background, rendering it invisible.
- First screenshot is the original view with orange as the button colour.
- Second screenshot is the preview of a white button.
- Third screenshot is the view of the test post with the white button (deleted immediately after screenshotting) compared to a "normal" post below.
<img width="659" alt="Screen Shot 2020-06-19 at 1 37 57 AM" src="https://user-images.githubusercontent.com/65053157/85100502-46f40d00-b1ce-11ea-8d32-edc93b1b0a2f.png">
<img width="724" alt="Screen Shot 2020-06-19 at 1 37 07 AM" src="https://user-images.githubusercontent.com/65053157/85100509-4a879400-b1ce-11ea-88b1-4ab6d5a18fae.png">
<img width="711" alt="Screen Shot 2020-06-19 at 1 38 31 AM" src="https://user-images.githubusercontent.com/65053157/85100518-4d828480-b1ce-11ea-8555-81743da2b7d3.png">

**Comment by MitchellArtz** [comment] 2020-06-21 02:11
Closing due to either:
1. Unimportant
2. Not Reproducible
3. Duplicate
4. Fixed

**Closed by MitchellArtz** 2020-06-21 02:11 UTC
Labels: enhancement, invalid
